print("________________________________________________________________________")
print("                        BREAD BASKET                    ")
print("Looking for a healthy breakfast, this is the place for you!!")
print("________________________________________________________________________")
print("Raisin Toast                                         $2.50")
print("French Toast                                         $2.80")
print("Mushroom Toast                                       $3.00")
print("Pancake                                              $4.00")
print("Pancake with Ice-cream                               $7.50")
print("Chef's speciality                                   $10.00")
print("__________________________________________________________________________")